return {
  -- "metalelf0/base16-black-metal-scheme",
  -- name = "black-metal",
  -- priority = 1000,
  -- config = function()
  --   -- base16-black-metal-scheme
  --   vim.cmd("colorscheme base16-black-metal")
  --
  --   -- Set transparent background for key highlight groups
  --   vim.api.nvim_set_hl(0, "Normal", { bg = nil, ctermbg = nil })
  --   vim.api.nvim_set_hl(0, "NormalFloat", { bg = nil, ctermbg = nil })
  --   vim.api.nvim_set_hl(0, "SignColumn", { bg = nil, ctermbg = nil })
  --   vim.api.nvim_set_hl(0, "LineNr", { bg = nil, ctermbg = nil })
  --   vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = nil, ctermbg = nil })
  --
  --   -- Brighten the comment color and other custom highlights
  --   vim.api.nvim_set_hl(0, "Comment", { fg = "#AAAAAA", bg = nil, italic = true })
  --   vim.api.nvim_set_hl(0, "@keyword", { fg = "#5f8787", bg = nil })
  --   vim.api.nvim_set_hl(0, "@keyword.return", { fg = "#a06666", bg = nil })
  --
  --   -- Define IblScope for indent-blankline.nvim
  --   vim.api.nvim_set_hl(0, "IblScope", { fg = "#5f8787", bg = nil }) -- Match @keyword color for consistency
  --
  --   -- Ensure transparency and custom highlights persist after colorscheme changes
  --   vim.api.nvim_create_autocmd("ColorScheme", {
  --     pattern = "*",
  --     callback = function()
  --       -- Reapply transparent background
  --       vim.api.nvim_set_hl(0, "Normal", { bg = nil, ctermbg = nil })
  --       vim.api.nvim_set_hl(0, "NormalFloat", { bg = nil, ctermbg = nil })
  --       vim.api.nvim_set_hl(0, "SignColumn", { bg = nil, ctermbg = nil })
  --       vim.api.nvim_set_hl(0, "LineNr", { bg = nil, ctermbg = nil })
  --       vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = nil, ctermbg = nil })
  --
  --       -- Reapply custom highlights
  --       vim.api.nvim_set_hl(0, "Comment", { fg = "#525252", bg = nil, italic = true })
  --       vim.api.nvim_set_hl(0, "@keyword", { fg = "#5f8787", bg = nil })
  --       vim.api.nvim_set_hl(0, "@keyword.return", { fg = "#a06666", bg = nil })
  --
  --       -- Reapply IblScope for indent-blankline.nvim
  --       vim.api.nvim_set_hl(0, "IblScope", { fg = "#5f8787", bg = nil })
  --     end,
  --   })
  -- end,
}
